### ISSUE TITLE
Injection failure

### ISSUE THREAD

**Issue by al-wei** [racoonman2/ReTerraForged#103]
`[10:25:51] [main/INFO]: ModLauncher running: args [--username, fanrenla, --version, 1.20.2, --gameDir, E:\Minecraft\G-BFS\1.20.2x\.minecraft, --assetsDir, E:\Minecraft\G-BFS\1.20.2x\.minecraft\assets, --assetIndex, 8, --uuid, 22a6563ab9313fc089ed6743993c09a6, --accessToken, �7�6�7�6�7�6�7�6�7�6�7�6�7�6�7�6, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, HMCL 3.5.9, --width, 854, --height, 480, --launchTarget, forge_client, --fml.forgeVersion, 48.1.0, --fml.mcVersion, 1.20.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230921.100330]
[10:25:51] [main/INFO]: JVM identified as Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 17.0.10+11-LTS-240
[10:25:51] [main/INFO]: ModLauncher 10.1.1 starting: java version 17.0.10 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[10:25:51] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[10:25:52] [main/INFO]: Trying GL version 4.6
[10:25:52] [main/INFO]: Requested GL version 4.6 got version 4.6
[10:25:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/Minecraft/G-BFS/1.20.2x/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT
[10:25:53] [main/INFO]: Found mod file reterraforged-0.0.7-forge-1.20.2.jar of type MOD with provider {mods folder locator at E:\Minecraft\G-BFS\1.20.2x\.minecraft\mods}
[10:25:53] [pool-2-thread-1/INFO]: GL info: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 561.09, NVIDIA Corporation
[10:25:53] [main/WARN]: Mod file E:\Minecraft\G-BFS\1.20.2x\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.2-48.1.0\fmlcore-1.20.2-48.1.0.jar is missing mods.toml file
[10:25:53] [main/WARN]: Mod file E:\Minecraft\G-BFS\1.20.2x\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.2-48.1.0\javafmllanguage-1.20.2-48.1.0.jar is missing mods.toml file
[10:25:53] [main/WARN]: Mod file E:\Minecraft\G-BFS\1.20.2x\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.2-48.1.0\lowcodelanguage-1.20.2-48.1.0.jar is missing mods.toml file
[10:25:53] [main/WARN]: Mod file E:\Minecraft\G-BFS\1.20.2x\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.2-48.1.0\mclanguage-1.20.2-48.1.0.jar is missing mods.toml file
[10:25:53] [main/INFO]: Found mod file fmlcore-1.20.2-48.1.0.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@400d912a
[10:25:53] [main/INFO]: Found mod file javafmllanguage-1.20.2-48.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@400d912a
[10:25:53] [main/INFO]: Found mod file lowcodelanguage-1.20.2-48.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@400d912a
[10:25:53] [main/INFO]: Found mod file mclanguage-1.20.2-48.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@400d912a
[10:25:53] [main/INFO]: Found mod file client-1.20.2-20230921.100330-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@400d912a
[10:25:53] [main/INFO]: Found mod file forge-1.20.2-48.1.0-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@400d912a
[10:25:53] [main/INFO]: No dependencies to load found. Skipping!
[10:25:54] [main/INFO]: Compatibility level set to JAVA_17
[10:25:54] [main/INFO]: Launching target 'forge_client' with arguments [--version, 1.20.2, --gameDir, E:\Minecraft\G-BFS\1.20.2x\.minecraft, --assetsDir, E:\Minecraft\G-BFS\1.20.2x\.minecraft\assets, --uuid, 22a6563ab9313fc089ed6743993c09a6, --username, fanrenla, --assetIndex, 8, --accessToken, �7�6�7�6�7�6�7�6�7�6�7�6�7�6�7�6, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, HMCL 3.5.9, --width, 854, --height, 480]
[10:25:54] [main/INFO]: Disabling TerraBlender compat
[10:25:54] [main/INFO]: Disabling World Preview compat
[10:25:55] [pool-4-thread-1/FATAL]: Mixin apply failed reterraforged-common.mixins.json:MixinChunkStatus -> net.minecraft.world.level.chunk.ChunkStatus: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on method_39464$HEAD could not find any targets matching 'method_39464' in net.minecraft.world.level.chunk.ChunkStatus. Using refmap reterraforged-common-refmap.json [PREINJECT Applicator Phase -> reterraforged-common.mixins.json:MixinChunkStatus -> Prepare Injections ->  -> handler$zzi000$method_39464$HEAD(Lnet/minecraft/world/level/chunk/ChunkStatus;Ljava/util/concurrent/Executor;Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/world/level/chunk/ChunkGenerator;Lnet/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplateManager;Lnet/minecraft/server/level/ThreadedLevelLightEngine;Ljava/util/function/Function;Ljava/util/List;Lnet/minecraft/world/level/chunk/ChunkAccess;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on method_39464$HEAD could not find any targets matching 'method_39464' in net.minecraft.world.level.chunk.ChunkStatus. Using refmap reterraforged-common-refmap.json [PREINJECT Applicator Phase -> reterraforged-common.mixins.json:MixinChunkStatus -> Prepare Injections ->  -> handler$zzi000$method_39464$HEAD(Lnet/minecraft/world/level/chunk/ChunkStatus;Ljava/util/concurrent/Executor;Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/world/level/chunk/ChunkGenerator;Lnet/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplateManager;Lnet/minecraft/server/level/ThreadedLevelLightEngine;Ljava/util/function/Function;Ljava/util/List;Lnet/minecraft/world/level/chunk/ChunkAccess;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:142) ~[modlauncher-10.1.1.jar:10.1.1]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:75) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:107) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:37) ~[modlauncher-10.1.1.jar:?]
	at net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:418) ~[securemodules-2.2.3.jar:?]
	at net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:367) ~[securemodules-2.2.3.jar:?]
	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:383) ~[securemodules-2.2.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:199) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:154) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
`

**Comment by racoonman2** [comment]
this isn’t ready for release yet and im not providing support for the old alpha builds

**Comment by al-wei** [comment]
> this isn’t ready for release yet and im not providing support for the old alpha builds

Is that so? I failed with 1.20.1, so I tried 1.20.2.

**Comment by al-wei** [comment]
> > this isn’t ready for release yet and im not providing support for the old alpha builds
> 
> Is that so? I failed with 1.20.1, so I tried 1.20.2.

But 1.20.2 still failed.

**Comment by equalizer32** [comment]
> > > this isn’t ready for release yet and im not providing support for the old alpha builds
> > 
> > 
> > Is that so? I failed with 1.20.1, so I tried 1.20.2.
> 
> But 1.20.2 still failed.

Yes, because it's not meant to be used right now. If you want to use RTF you have to wait for the next update.
