### ISSUE TITLE
Crashing with Ticking World Entity Error

### ISSUE THREAD

**Issue by Freyr-VM** [racoonman2/ReTerraForged#90]
---- Minecraft Crash Report ----

// Hi. I'm Connector, and I'm a crashaholic
=========================
SINYTRA CONNECTOR IS PRESENT!
Please verify issues are not caused by Connector before reporting them to mod authors.
If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.
=========================

// Quite honestly, I wouldn't worry myself about that.

Time: 2024-06-30 05:47:52
Description: Exception ticking world

java.lang.NoClassDefFoundError: Could not initialize class raccoonman.reterraforged.world.worldgen.cell.Cell
	at raccoonman.reterraforged.world.worldgen.densityfunction.CellSampler$Cache2d.<init>(CellSampler.java:50) ~[Reterraforged-Mod-Forge-1.20.1.jar%23480!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.levelgen.NoiseChunk.redirect$clm000$reterraforged$NoiseChunk(NoiseChunk.java:1508) ~[server-1.20.1-20230612.114412-srg.jar%23519!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:reterraforged-common.mixins.json:terrablender.MixinNoiseChunk from mod reterraforged,pl:mixin:APP:reterraforged-common.mixins.json:MixinNoiseChunk from mod reterraforged,pl:mixin:APP:fabric-biome-api-v1.mixins.json:ChunkNoiseSamplerMixin from mod fabric_biome_api_v1,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.levelgen.NoiseChunk.<init>(NoiseChunk.java:162) ~[server-1.20.1-20230612.114412-srg.jar%23519!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:reterraforged-common.mixins.json:terrablender.MixinNoiseChunk from mod reterraforged,pl:mixin:APP:reterraforged-common.mixins.json:MixinNoiseChunk from mod reterraforged,pl:mixin:APP:fabric-biome-api-v1.mixins.json:ChunkNoiseSamplerMixin from mod fabric_biome_api_v1,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.levelgen.NoiseChunk.m_224352_(NoiseChunk.java:111) ~[server-1.20.1-20230612.114412-srg.jar%23519!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:reterraforged-common.mixins.json:terrablender.MixinNoiseChunk from mod reterraforged,pl:mixin:APP:reterraforged-common.mixins.json:MixinNoiseChunk from mod reterraforged,pl:mixin:APP:fabric-biome-api-v1.mixins.json:ChunkNoiseSamplerMixin from mod fabric_biome_api_v1,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_224256_(NoiseBasedChunkGenerator.java:107) ~[server-1.20.1-20230612.114412-srg.jar%23519!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:NoiseBasedChunkGeneratorMixin from mod citadel,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_224336_(NoiseBasedChunkGenerator.java:99) ~[server-1.20.1-20230612.114412-srg.jar%23519!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:NoiseBasedChunkGeneratorMixin from mod citadel,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.chunk.ChunkAccess.m_223012_(ChunkAccess.java:397) ~[server-1.20.1-20230612.114412-srg.jar%23519!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.ticking_chunk_alloc.ChunkAccessMixin from mod modernfix,pl:mixin:APP:starlight.mixins.json:common.chunk.ChunkAccessMixin from mod starlight,pl:mixin:APP:smoothchunk.mixins.json:ChunkAccessMixin from mod smoothchunk,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:AttachmentTargetsMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:structure_gel.mixins.json:ChunkAccessMixin$Access from mod structure_gel,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_224291_(NoiseBasedChunkGenerator.java:99) ~[server-1.20.1-20230612.114412-srg.jar%23519!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:NoiseBasedChunkGeneratorMixin from mod citadel,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_224331_(NoiseBasedChunkGenerator.java:93) ~[server-1.20.1-20230612.114412-srg.jar%23519!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:NoiseBasedChunkGeneratorMixin from mod citadel,pl:mixin:A,pl:connector_pre_launch:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /opt/java/openjdk/lib/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory [in thread "Worker-Main-2"]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[?:?] {}
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418) ~[?:?] {}
	at java.lang.Runtime.load0(Runtime.java:852) ~[?:?] {}
	at java.lang.System.load(System.java:2025) ~[?:?] {re:mixin}
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:249) ~[?:?] {}
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427) ~[?:?] {}
	at java.lang.Runtime.loadLibrary0(Runtime.java:916) ~[?:?] {}
	at java.lang.System.loadLibrary(System.java:2063) ~[?:?] {re:mixin}
	at java.awt.Toolkit$2.run(Toolkit.java:1384) ~[?:?] {}
	at java.awt.Toolkit$2.run(Toolkit.java:1382) ~[?:?] {}
	at java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?] {}
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1381) ~[?:?] {}
	at java.awt.Toolkit.initStatic(Toolkit.java:1419) ~[?:?] {}
	at java.awt.Toolkit.<clinit>(Toolkit.java:1393) ~[?:?] {}
	at java.awt.Color.<clinit>(Color.java:277) ~[?:?] {}
	at raccoonman.reterraforged.world.worldgen.cell.biome.type.BiomeType.<clinit>(BiomeType.java:13) ~[Reterraforged-Mod-Forge-1.20.1.jar%23480!/:?] {re:classloading,pl:redirector:A}
	at raccoonman.reterraforged.world.worldgen.cell.Cell.<init>(Cell.java:57) ~[Reterraforged-Mod-Forge-1.20.1.jar%23480!/:?] {re:classloading}
	at raccoonman.reterraforged.world.worldgen.cell.Cell.<clinit>(Cell.java:11) ~[Reterraforged-Mod-Forge-1.20.1.jar%23480!/:?] {re:classloading}
	... 16 more

**Comment by equalizer32** [comment]
Please, isolate the issue before posting an incomplete crash log on the GitHub. This crash report is useless.
